replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  loadBalancerClass:
  type: ClusterIP
  ports:
    - sourcePort: 80
      targetPort: http
      protocol: TCP
      name: http
  annotations: {}

health:
  name: healthcheck

ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: your-hostname.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: your-host-tls
  #    hosts:
  #      - your-hostname.local

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# This is where your nginx server block goes
#siteConfig: |-
#  server {
#    listen 0.0.0.0:80;
#    location / {
#      add_header Content-Type text/plain;
#      return 200 'Whoopwhoop';
#    }
#  }
nginx:
  ports:
    - name: http
      port: 80
      protcol: TCP
    - name: healh
      port: 8080
      protocol: TCP
  config: ""
  siteConfig: ""
  tempDir: "/var/run/nginx"

metrics:
  enabled: true
  port: 9113
