apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
      {{- include "keycloak.labels" . | nindent 4 }}
data:
  EXTERNAL_URL: {{ include "keycloak.externalUrl" . }}
  URL: {{ include "keycloak.internalUrl" . }}