apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
      {{- include "keycloak.labels" . | nindent 4 }}
data:
  EXTERNAL_URL: {{ .Values.host }}{{ .Values.ingress.path | trimSuffix "/" }}
  URL: {{ include "keycloak.serviceName" . }}:{{ .Values.service.port }}{{ .Values.ingress.path | trimSuffix "/" }}