{{- $host := .Values.host | required ".Values.host is required." -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- range $key, $value := .Values.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["start", "--hostname", {{ .Values.host | quote }}]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /realms/master
              port: {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.admin.username }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.admin.password }}
            {{- if .Values.database.external }}
            - name: KC_DB
              value: {{ .Values.database.vendor }}
            - name: KC_DB_USERNAME
              value: {{ .Values.database.username }}
            - name: KC_DB_PASSWORD
              value: {{ .Values.database.password }}
            - name: KC_DB_URL
              value: {{ .Values.database.url }}
            {{ end }}
