# k8s secret for keycloak admin username and password
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ .Values.admin.username | b64enc | quote }}
  KEYCLOAK_PASSWORD: {{ .Values.admin.username | b64enc | quote }}

---
{{- if .Values.database.external }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-database-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  KC_DB: {{ .Values.database.vendor | b64enc | quote }}
  KC_DB_USERNAME: {{ .Values.database.username | b64enc | quote }}
  KC_DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  KC_DB_URL: {{ .Values.database.url | b64enc | quote }}
{{- end}}