nameOverride: ""
fullnameOverride: ""

image:
  tag: ""

serviceName: "test-tracing-app"
servicePort: 8080

otel:
  agentUrl: "http://tempo-agent:4317"
  applicationName: "test-tracing-app"
  protocol: "otlp"
  tenant_id: ""