{{/*
Common Helper generated by helm.
*/}}

{{/*
Expand the name of the chart.
*/}}
{{- define "prometheus-agent.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "prometheus-agent.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "prometheus-agent.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "prometheus-agent.labels" -}}
helm.sh/chart: {{ include "prometheus-agent.chart" . }}
{{ include "prometheus-agent.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "prometheus-agent.selectorLabels" -}}
app.kubernetes.io/name: {{ include "prometheus-agent.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "prometheus-agent.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "prometheus-agent.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}
{{- define "prometheus-agent.commonAnnotations" -}}
{{- with .Values.commonAnnotations }}
{{ toYaml . }}
{{- end }}
{{- end -}}

{{/*
Kubernetes pods relabel configs
Params:
  - nameLabelOverride: optional label override for the job label
  - scrapeAnnotation: the annotation to check for scraping (e.g., "prometheus_io_scrape" or "prometheus_io_scrape_1m")
*/}}
{{- define "prometheus-agent.podRelabelConfigs" -}}
{{- $nameLabelOverride := .nameLabelOverride }}
{{- $scrapeAnnotation := .scrapeAnnotation }}
# Make Scheme configurable by setting prometheus.io/scheme
- source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scheme ]
  action: replace
  target_label: __scheme__
  regex: (https?)
# Scrape metrics when the {{ $scrapeAnnotation | replace "_" "." }} annotation has been set to true
- source_labels: [ __meta_kubernetes_pod_annotation_{{ $scrapeAnnotation }} ]
  action: keep
  regex: true
# Allow us to overwrite the path with the content of prometheus.io/path
- source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_path ]
  action: replace
  target_label: __metrics_path__
  regex: (.+)
# Allow us to overwrite the default path with the content of prometheus.io/port
- source_labels: [ __address__, __meta_kubernetes_pod_annotation_prometheus_io_port ]
  action: replace
  regex: ([^:]+)(?::\d+)?;(\d+)
  replacement: ${1}:${2}
  target_label: __address__
# Expose Pod labels as metric labels
- action: labelmap
  regex: __meta_kubernetes_pod_label_app_kubernetes_io_(.+)
- action: labelmap
  regex: __meta_kubernetes_pod_label_(.+)
# Expose Pod namespace as metric namespace label
- source_labels: [ __meta_kubernetes_namespace ]
  action: replace
  target_label: namespace
# Expose Pod name as metric name label
- source_labels: [ __meta_kubernetes_pod_name ]
  action: replace
  target_label: pod
{{- if $nameLabelOverride }}
- source_labels: [ __meta_kubernetes_namespace, __meta_kubernetes_pod_label_{{$nameLabelOverride}}]
{{- else}}
- source_labels: [ __meta_kubernetes_namespace, __meta_kubernetes_pod_label_name ]
{{- end}}
  action: replace
  separator: /
  target_label: job
  replacement: $1
{{- end -}}
