apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-agent.fullname" . }}
  labels:
    {{- include "prometheus-agent.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - name: "http-metrics"
      port: 80
      targetPort: 80
  selector:
    {{- include "prometheus-agent.selectorLabels" . | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prometheus-agent.fullname" . }}
  labels:
    {{- include "prometheus-agent.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "prometheus-agent.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "prometheus-agent.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "prometheus-agent.labels" . | nindent 8 }}
    spec:
      containers:
        - args:
            - -config.file=/etc/agent/agent.yaml
            - -enable-features=integrations-next
            - -server.http.address=0.0.0.0:80
          command:
            - /bin/agent
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: "grafana/agent:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          name: {{ .Chart.Name }}
          ports:
            - containerPort: 80
              name: http-metrics
          volumeMounts:
            - mountPath: /var/lib/agent
              name: agent-wal
            - mountPath: /etc/agent
              name: {{ include "prometheus-agent.fullname" . }}
      serviceAccountName: {{ include "prometheus-agent.serviceAccountName" . }}
      volumes:
        - configMap:
            name: {{ include "prometheus-agent.fullname" . }}
          name: {{ include "prometheus-agent.fullname" . }}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: agent-wal
        namespace: {{ .Release.Namespace }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
