apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  default.conf: |-
    server {
      listen {{ .Values.health.port }};
      server_name localhost;
      location /metrics {
        stub_status;
        allow 127.0.0.1;
        deny all;
      }
    }
  user_site.conf: |-
  {{ .Values.siteConfig | nindent 4}}
