apiVersion: v1
kind: ConfigMap
metadata:
  name: site-config
data:
  default.conf: |-
    server {
      listen {{ .Values.health.port }};
      server_name localhost;
      location / {
        access_log off;
        add_header 'Content-Type' 'application/json';
        return 200 '{"status":"UP"}';
      }
      location /metrics {
        access_log off;
        stub_status;
        allow 127.0.0.1;
        deny all;
      }
    }
  user_site.conf: |-
  {{ .Values.nginx.siteConfig | nindent 4}}
