image:
  repository: grafana/agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""




remote_write: |
  - url: YOUR_PROMETHEUS_REMOTE_WRITE_URL
    basic_auth:
      username: YOUR_PROMETHEUS_REMOTE_WRITE_USERNAME
      password: YOUR_PROMETHEUS_REMOTE_WRITE_PASSWORD
