{{- if ne .Values.image.credentials.password "" }}
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}


