apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (include "strapi.fullname" .) }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeName: {{ default (include "strapi.fullname" .) }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ default (include "strapi.fullname" .) }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Reclaim
  storageClassName: {{ .Values.persistence.storageClass }}
  claimRef:
    name: {{ default (include "strapi.fullname" .) }}
    namespace: {{ .Release.Namespace }}
