apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "imagereporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "imagereporter.labels" . | nindent 6 }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "imagereporter.selectorLabels" . | nindent 8 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
      labels:
        {{- include "imagereporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: '847164143281.dkr.ecr.eu-central-1.amazonaws.com/kubernetes-imagereporter:{{ .Values.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: metrics

