apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prometheus-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prometheus-agent.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
      - events
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "prometheus-agent.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-agent
subjects:
  - kind: ServiceAccount
    name: grafana-agent
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ include "prometheus-agent.fullname" . }}
  name: {{ include "prometheus-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
    - name: grafana-agent-http-metrics
      port: 80
      targetPort: 80
  selector:
    name: {{ include "prometheus-agent.fullname" . }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "prometheus-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "prometheus-agent.fullname" . }}
  serviceName: {{ include "prometheus-agent.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ include "prometheus-agent.fullname" . }}
    spec:
      containers:
        - args:
            - -config.file=/etc/agent/agent.yaml
            - -enable-features=integrations-next
            - -server.http.address=0.0.0.0:80
          command:
            - /bin/agent
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          name: {{ include "prometheus-agent.fullname" . }}
          ports:
            - containerPort: 80
              name: http-metrics
          volumeMounts:
            - mountPath: /var/lib/agent
              name: agent-wal
            - mountPath: /etc/agent
              name: {{ include "prometheus-agent.fullname" . }}
      serviceAccount: grafana-agent
      volumes:
        - configMap:
            name: grafana-agent
          name: grafana-agent
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: agent-wal
        namespace: {{ .Release.Namespace }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
