kind: ConfigMap
metadata:
  name: {{ include "tempo-agent.fullname" . }}
  labels:
    {{- include "tempo-agent.labels" . | nindent 4 }}
apiVersion: v1
data:
  agent.yaml: |
    traces:
      configs:
        - batch:
            send_batch_size: 1000
            timeout: 5s
          name: default
          receivers:
            jaeger:
              protocols:
                grpc: null
                thrift_binary: null
                thrift_compact: null
                thrift_http: null
              remote_sampling:
                strategy_file: /etc/agent/strategies.json
                tls:
                  insecure: true
            opencensus: null
            otlp:
              protocols:
                grpc: null
                http: null
            zipkin: null
          remote_write:
             {{- range .Values.remote_write }}
            - basic_auth:
                password: '{{.basic_auth.password}}'
                username: '{{.basic_auth.username}}'
              endpoint: {{ .endpoint }}:80/otlp
              {{- if .tenant_id}}
              headers:
                X-Scope-OrgId: '{{.tenant_id}}'
              {{- end }}
              {{- if .useGrpc }}
              protocol: grpc
              {{- else }}
              protocol: http
              {{- end }}
              retry_on_failure:
                enabled: {{.retry_on_failure.enabled}}
              insecure: true
            {{- end }}
          scrape_configs:
            - bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
              job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - action: replace
                  source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - action: replace
                  source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
              tls_config:
                ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                insecure_skip_verify: false
  strategies.json: '{"default_strategy": {"param": 0.001, "type": "probabilistic"}}'