apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "tempo-agent.fullname" . }}
  labels:
    {{- include "tempo-agent.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "tempo-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tempo-agent.labels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - -config.file=/etc/agent/agent.yaml
        - -server.http.address=0.0.0.0:80
        command:
        - /bin/agent
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: "grafana/agent:{{ .Chart.AppVersion }}"
        imagePullPolicy: IfNotPresent
        name:  {{ .Chart.Name }}
        ports:
        - containerPort: 80
          name: http-metrics
        - containerPort: 6831
          name: thrift-compact
          protocol: UDP
        - containerPort: 6832
          name: thrift-binary
          protocol: UDP
        - containerPort: 14268
          name: thrift-http
          protocol: TCP
        - containerPort: 14250
          name: thrift-grpc
          protocol: TCP
        - containerPort: 9411
          name: zipkin
          protocol: TCP
        - containerPort: 4317
          name: otlp
          protocol: TCP
        - containerPort: 55678
          name: opencensus
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/agent
          name: {{ include "tempo-agent.fullname" . }}
      serviceAccountName: {{ include "tempo-agent.serviceAccountName" . }}
      volumes:
      - configMap:
          name: {{ include "tempo-agent.fullname" . }}
        name: {{ include "tempo-agent.fullname" . }}