{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tempo-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo-agent.labels" . | nindent 4 }}
  annotations:
    {{- include "tempo-agent.commonAnnotations" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tempo-agent.serviceAccountName" . }}
  labels:
    {{- include "tempo-agent.labels" . | nindent 4 }}
  annotations:
    {{- include "tempo-agent.commonAnnotations" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - events
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tempo-agent.serviceAccountName" . }}
  labels:
    {{- include "tempo-agent.labels" . | nindent 4 }}
  annotations:
    {{- include "tempo-agent.commonAnnotations" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tempo-agent.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "tempo-agent.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
