apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo-agent.fullname" . }}
  labels:
    {{- include "tempo-agent.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "tempo-agent.commonAnnotations" . | nindent 4 }}
spec:
  ports:
    - name: traces-http-metrics
      port: 80
      targetPort: 80
    - name: traces-thrift-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: traces-thrift-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: traces-thrift-http
      port: 14268
      protocol: TCP
      targetPort: 14268
    - name: traces-thrift-grpc
      port: 14250
      protocol: TCP
      targetPort: 14250
    - name: traces-zipkin
      port: 9411
      protocol: TCP
      targetPort: 9411
    - name: traces-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: traces-opencensus
      port: 55678
      protocol: TCP
      targetPort: 55678
  selector:
    {{- include "tempo-agent.selectorLabels" . | nindent 4 }}
  internalTrafficPolicy: Local
