kind: ConfigMap
apiVersion: v1
metadata:
  name: cloudprober-config
  labels:
    {{- include "cloudprober.labels" . | nindent 4 }}
data:
  cloudprober.cfg: |+
    surfacer {
      type: PROMETHEUS

        prometheus_surfacer {
        # Following option adds a prefix to exported metrics, for example,
        # "total" metric is exported as "cloudprober_total".
        metrics_prefix: "cloudprober_"
      }
    }
    {{ range .Values.probes }}
    probe {
      name: "{{.name}}"
      type: {{.type}}
      targets {
        {{- if eq (len .targets.host_names) 1 }}
        host_names: {{- range .targets.host_names -}} "{{.}}" {{end -}}
        {{- else }}
        host_names: [{{- range .targets.host_names -}} "{{ . }}" {{ end -}}]
        {{- end }}
      }
      http_probe {}
      interval_msec: {{.interval}}
      timeout_msec: {{.timeout}}
      {{- if .validators }}
      {{- range .validators }}
      validator {
        name: "{{ .name }}"
        {{- .validator_config | nindent 8 }}
      }
      {{- end }}
      {{- end }}
    }
    {{end}}